### ISSUE TITLE
Support for dark theme(s)

### ISSUE THREAD

**Issue by DavidDeSloovere** [solidify/vsts-extension-chuck-norris#12]
Hello,

Now that Azure DevOps supports themes, Chuck Norris doesn't look so good anymore 😄 .
He might just be making a stand on dark themes not being cool. But regular humans might like it. 

![image](https://user-images.githubusercontent.com/352626/57533700-ae3e5d00-733e-11e9-9645-94d3fb2f0e0b.png)

**Comment by MOlausson** [comment]
Ah, @DavidDeSloovere, this cannot do :) I'll see what we can do to get Chuck back in shape. Not that he need it of course!
