### ISSUE TITLE
Can't install in TFS on-prem

### ISSUE THREAD

**Issue by jmezach** [solidify/vsts-extension-chuck-norris#5]
This is a must have for us, unfortunately we can't install the extension into our on-premises TFS server ;)

**Comment by MOlausson** [comment]
Ah, too bad :( The extension is depending on an api that was introduced to VSTS quite recently, I will have to check from which TFS version it is available. What version are you on?

**Comment by jmezach** [comment]
@MOlausson We are running the latest stable version (TFS 2017 Update 2). What API are you using out of curiosity ;)

We do have a cloned production environment that is running 2018 RC2, so I might be able to try it out there (if it's even possible to publish an extension that targets 2018 RC2 ;))

**Comment by jmezach** [comment]
I just tried to install this extension by building the vsix myself on a fresh clone and then upload it to our test 2018 server. Unfortunately that gives me an error indicating that the extension manifest or package is corrupt. Not sure what's going on there, any ideas?

**Comment by MOlausson** [comment]
Finally got around to look at this. As of version 0.2.4 TFS is also supported (version 2018 update 2 and later because of the versions of apis used in the extension).
