### ISSUE TITLE
Using the new preview of VSTS, the quote shows in the build log, but disappears when you bring it completely into view

### ISSUE THREAD

**Issue by philcarbone** [solidify/vsts-extension-chuck-norris#6]
I tried to capture a screenshot or capture in the DOM, but couldn't find it.

You see it for a split second when you scroll to the bottom of the screen, but it disappears right after.

Here is the screen after it was lost:
![image](https://user-images.githubusercontent.com/5216301/44167180-79e18d00-a09b-11e8-9e9f-e564d14599a6.png)

**Comment by MOlausson** [comment]
Finally got around to look at this, seems to be due to changes in the way we can add custom report sections to the pipelines logs. I'll get an update out soon.

**Comment by MOlausson** [comment]
This is resolved as of version 0.2.4 of the task.
